# Generated by Django 4.1.5 on 2023-02-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_checkoutproducts_qty_checkoutproducts_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutproducts',
            old_name='P',
            new_name='p',
        ),
    ]
