# Generated by Django 4.1.5 on 2023-02-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_buyer_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(default=-1151515),
        ),
    ]
